//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int idPartida { get; set; }
        public int idUsuario1 { get; set; }
        public int idUsuario2 { get; set; }
        public int tipoPartida { get; set; }
        public Nullable<int> etapa { get; set; }
    
        public virtual Empate Empate { get; set; }
        public virtual Etapa Etapa1 { get; set; }
        public virtual Ganador Ganador { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual TipoDePartida TipoDePartida { get; set; }
        public virtual Perdedor Perdedor { get; set; }
    }
}
