//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Partida = new HashSet<Partida>();
            this.Partida1 = new HashSet<Partida>();
            this.Torneo = new HashSet<Torneo>();
            this.Torneo1 = new HashSet<Torneo>();
            this.Etapa = new HashSet<Etapa>();
        }
    
        public int idUsuario { get; set; }
        [Display(Name = "Nombre"), Required(ErrorMessage = "Nombre es requerido")]
        public string nombre { get; set; }
        [Display(Name = "Apellido"), Required(ErrorMessage = "Apellido es requerido")]
        public string apellido { get; set; }
        [Display(Name = "Nombre de Usuario"), Required(ErrorMessage = "Nombre de usuario es requerido")]
        public string nombreUsuario { get; set; }
        [Display(Name = "Contraseña"), Required(ErrorMessage = "Contraseña es requerida"), DataType(DataType.Password)]
        public string contrasenia { get; set; }
        [Display(Name = "Fecha de Nacimiento"), Required(ErrorMessage = "La fecha de nacimiento es requerida")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="0:yyyy-MM-dd", ApplyFormatInEditMode =true)]
        public System.DateTime fechaNacimiento { get; set; }
        [Display(Name = "Correo"), Required(ErrorMessage = "Correo es requerido"), DataType(DataType.EmailAddress)]
        public string correo { get; set; }
        [Display(Name = "Pais"), Required(ErrorMessage = "Pais es requerido")]
        public int pais { get; set; }
    
        public virtual Pais Pais1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida> Partida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida> Partida1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneo> Torneo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneo> Torneo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etapa> Etapa { get; set; }
    }
}
